# Introduction to [Julia](https://www.julialang.org)


<img src="pics/julia.png" alt="Julia Logo" width="300">


> "Julia is the fastest modern open-source language for data science, machine learning and scientific computing. Julia provides the functionality, ease-of-use and intuitive syntax of R, Python, Matlab, SAS or Stata combined with the speed, capacity and performance of C, C++ or Java."

## Table of Contents
* [Installation](#installation)
    * [JuliaBox](#juliabox)
    * [Julia Kernel](#juliakernel)
    * [Jupiter Notebooks](#ijulia)
    * [Atom Text Editor & Juno](#atom)
    * [Packages](#packages)
* [Essentials](#essentials)
* [Arrays and Matrices](#arraysandmatrices)
    * [Creating arrays (and matrices)](#creatingarrays)
    * [Calculating with arrays (and matrices)](#calculating)
    * [Manipluating arrays (and matrices)](#manipulatearray)
    * [Subsetting arrays (and matrices)](#subsetting)

* [Conditionals](#conditionals)
* [Control flow](#controlflow)
* [Comprehensions](#comprehensions)
* [Random Walk example](#randomwalk)

## Installation <a class="anchor" id="installation"></a>
Links on how to install Julia and JuMP you find in the ISIS course, e.g. https://datatofish.com/add-julia-to-jupyter/

<img src="pics/installation.png" alt="installation screenshot" width="600">


### JuliaBox <a class="anchor" id="juliabox"></a>
You can use Julia directly in your browser using the free [JuliaBox](https://juliabox.com/). **Unfortunately the free service is going to be cancelled by the end of October, so you all need to install Julia locally.**

### Julia Kernel <a class="anchor" id="juliakernel"></a>

In order to install the Julia language download the [latest release](https://julialang.org/downloads/) (currently 1.2.0). Use the command line version for your OS. In this example we are using the Windows 64bit version.

After starting Julia the shell can be directly used as a REPL (Read-Eval-Print Loop).

### IJulia: Jupyter Notebooks <a class="anchor" id="ijulia"></a>
What you see here is a Jupyter Notebook. Use the Package `IJulia` to install Jupyter Notebook (will automatically install an instance of Python). You will find this in the installation guide as well.


### Packages <a class="anchor" id="packages"></a>

Packages extend the functionality of Julia. You can manage your packages using the Pkg-Package 😁. Before you can use it you always have to initialize a package here:
`using Pkg`

The following functionality is available:

`Pkg.add(??)` adds a package

`Pkg.rm(??)` removes a package

`Pkg.update()` updates all installed packages (careful with this one!)

`Pkg.status()` gives an overview of installed packages and their version

In [2]:
using Pkg
Pkg.status()

    Status `C:\Users\Lissy\.julia\environments\v1.2\Project.toml`
  [c52e3926] Atom v0.11.0
  [336ed68f] CSV v0.5.12
  [a93c6f00] DataFrames v0.19.4
  [60bf3e95] GLPK v0.10.0
  [2e9cd046] Gurobi v0.6.0
  [7073ff75] IJulia v1.20.0
  [4076af6c] JuMP v0.19.2
  [e5e0dc1b] Juno v0.7.2
  [6405355b] Mosek v1.0.4
  [1ec41992] MosekTools v0.8.0
  [91a5bcdd] Plots v0.26.3
  [f3b207a7] StatsPlots v0.12.0
  [9a3f8284] Random 


### Packages we'll use frequently

#### Plots

For plotting in Julia we use the [StatsPlots.jl](https://github.com/JuliaPlots/StatsPlots.jl) package as a way to describe the plots. See also the notebook on visualization in Julia.


In [3]:
#Pkg.add("StatsPlots")

#### JuMP

> "An algebraic modeling language for linear, quadratic, and nonlinear constrained optimization problems embedded in Julia. Generates models as quick as commercial modeling tools and supports advanced features like solver callbacks."

In [4]:
#Pkg.add("JuMP")

#### Open-source Solvers

GLPK, IPOPT, Clp, and Cbc are open-source solvers that can be used with JuMP.

In [5]:
#Pkg.add("GLPK")

# Essentials <a class="anchor" id="essentials"></a>

In [7]:
println("hello world")

hello world


In [8]:
# single line comment

#=
Multiline comment
fjoiewhfoe
=#

In [9]:
a = "hello world"

println(a)

hello world


In [10]:
typeof(a)

String

Basic operations work as you would expect it.

$$ 2+2 $$

In [11]:
2 + 2

4

$$ 2 \ast 2 $$

In [12]:
2*2

4

$$ \dfrac{1}{2} $$

In [13]:
1/2

0.5

$$ 2 ^{2}  $$

In [14]:
2^2

4

$$ 5 > 2 $$

In [15]:
5 > 2

true

$$ 5 = 2 $$

In [16]:
5 == 2

false

$$ 5 \neq 2 $$

In [17]:
5 != 2

true

In [18]:
a = 5
b = 2
both = a + b

7

In [19]:
typeof(both)

Int64

In [20]:
both += 0.5

7.5

In [21]:
typeof(both)

Float64

In [22]:
c = a * b
d = c / 2

d

5.0

# Arrays & Matrices <a class="anchor" id="arraysandmatrices"></a>

### Creating arrays (and matrices) <a class="anchor" id="createarray"></a>

A simple array can be created with squared brackets.

In [23]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

The same syntax without commas as seperator creates a 1x3 array.

In [24]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

New lines in matrices are marked with ` ; `. Alternatively, the same matrix can be created by starting a new line.

In [25]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [26]:
[1 2
 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

Assigned variables can also be put into an array.

In [27]:
vec = [a, b, c]

3-element Array{Int64,1}:
  5
  2
 10

### Calculating with arrays (and matrices) <a class="anchor" id="calculating"></a>

In [28]:
2 * vec

3-element Array{Int64,1}:
 10
  4
 20

However, multiplying two arrays [3x1] * [3x1] does not work because of the dimensions!

In [29]:
[1,2,3] * vec

MethodError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(!Matched::LinearAlgebra.Adjoint{#s617,#s616} where #s616<:Union{DenseArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2}, Base.ReinterpretArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s617, ::Union{DenseArray{S,1}, Base.ReinterpretArray{S,1,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{S,1,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{S,1,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where {T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64}, S} at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\LinearAlgebra\src\matmul.jl:99
  *(!Matched::LinearAlgebra.Adjoint{#s617,#s616} where #s616<:LinearAlgebra.AbstractTriangular where #s617, ::AbstractArray{T,1} where T) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\LinearAlgebra\src\triangular.jl:1850
  ...

In [30]:
@show [1,2,3]' * vec
@show [1,2,3] * vec';

([1, 2, 3])' * vec = 39
[1, 2, 3] * vec' = [5 2 10; 10 4 20; 15 6 30]


You can multiply two one-dimensional arrays by using the `.` Syntax. Julia then knows that each element at the same position should be mulitplied.

In [31]:
[1, 2, 3] .* vec

3-element Array{Int64,1}:
  5
  4
 30

Elementwise addition works in the same.

In [32]:
[1, 2, 3] .+ 1

3-element Array{Int64,1}:
 2
 3
 4

In [33]:
[1, 2, 3] .+ [1, 2, 3]

3-element Array{Int64,1}:
 2
 4
 6

In [34]:
vec = [1,2,3,4,5,6,7,8]

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [35]:
sum(vec)

36

In [36]:
prod(vec)

40320

In [37]:
map(x-> x^2 - 1, vec)

8-element Array{Int64,1}:
  0
  3
  8
 15
 24
 35
 48
 63

In [38]:
matrix = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [39]:
matrix'

3×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [40]:
sum(matrix, dims=1)

1×3 Array{Int64,2}:
 5  7  9

In [41]:
?sum # help function

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr)
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(1:20)
210
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, dims=2)
2×1 Array{Int64,2}:
 3
 7
```
